### PR TITLE
Add Rust lang support for the new 1.0 verion of the uuid crate.

### PR DESCRIPTION
**Pull request by VegetarianOrc**
Adds support for the new 1.0 version of the [`uuid`](https://crates.io/crates/uuid) crate under the feature flag `uuid-10`.

The feature constrains versions of the `uuid` crate to `>=1.0.0, < 2.0.0` assuming that the API will remain stable for the lifetime of the major version.

### CODE REVIEW

**Comment by samscott89** [comment]
Hey @VegetarianOrc ! Thanks for the PR. This is looking good. If you can sign the CLA, we should be able to merge this :)

**Review by samscott89 — APPROVED** [review]
This looks good! Can merge once the CLA has been agreed to.

**Comment by VegetarianOrc** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by VegetarianOrc** [comment]
Hey @samscott89 sorry for the delay on signing! Good to go!

**Pull request merged**
