### PR TITLE
Add support for loading policy files from the resources folder.

### PR DESCRIPTION
**Pull request by kovacstamasx**
**Rationale**
Policy file loading was handled via filesystem path.
That works fine until you package your application to a jar file.

Further details can be found on Slack: https://oso-oss.slack.com/archives/C017KSBTD4M/p1636489557243600

**Scope**
This PR adds support for loading policy files from the resources folder.

**Open Questions**
- Do I have to add a changelog entry?
- Do I have to increase the version number of the library?

PR checklist:

- [ ] Added changelog entry.

### CODE REVIEW

**Comment by kovacstamasx** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by patrickod** [comment]
hey @kovacstamasx thank you very much for the contribution! I have cut a PR #1554 which applies some auto-formatting to pass our `development` check and which will merge this into an upcoming release.

RE your questions:
* I'm going to add a CHANGELOG entry to the #1554 we're 👍🏻 without one here.
* we will hold the version number increase until our next library release. We have been focusing our efforts on a substantial new product development at the moment so I am unable to detail exactly when that will be, but I hope it to be sometime in the near future.

thanks again for your work on this issue. We (and other Java users) are very grateful for your contribution.

**Comment by hobofan** [comment]
@kovacstamasx Just as a heads up: I think you might have accidentally merged the commit to your private artifact registry into the branch that forms the basis for this PR.

**Comment by kovacstamasx** [comment]
@hobofan 
> @kovacstamasx Just as a heads up: I think you might have accidentally merged the commit to your private artifact registry into the branch that forms the basis for this PR.
> 
> EDIT: Though I guess that might not matter if #1554 ends up being the PR that is merged 🤦

You're right so I reverted that change.
However it hasn't propagated to #1554 but still...it shouldn't be here.

**Comment by samscott89** [comment]
Going to merge this in #1554

**Pull request closed without merging**
