### PR TITLE
changelog stuff

### PR DESCRIPTION
**Pull request by saolsen**

### CODE REVIEW

**Review by gj — CHANGES_REQUESTED** [review]
This should go into 0.5.2.rst (after #410 merges)

**Comment by gj** [comment]
on second thought, since I need to fix spelling on #410 I'll just add this line to the changelog in that PR.

**Comment by gj** [comment]
Added in 5158a7e35c3b920be8331a1e9c198451dc20cf05

**Comment by gj** [comment]
Let's re-purpose this PR as the version bump from 0.5.1 -> 0.5.2?

**Comment by samscott89** [comment]
Will do version bump separate.

**Pull request closed without merging**
