### PR TITLE
Only upload our wheels to pypi

### PR DESCRIPTION
**Pull request by gkaemmer**

### CODE REVIEW

**Review by gj — APPROVED** [review]

**Review by gj — CHANGES_REQUESTED** [review]
1 sec

**Review by gj — APPROVED** [review]

**Review by gj — CHANGES_REQUESTED** [review]
oh wait I forgot we were gonna strip out other wheels first

**Review by gj — COMMENTED** [review]
@gkaemmer can we do a test run w/ the new code (w/ the "upload release" step commented out so we can inspect the artifacts on the workflow page but don't actually create new releases on GitHub)? It LGTM but would rather be certain

**Comment by gkaemmer** [comment]
> @gkaemmer can we do a test run w/ the new code (w/ the "upload release" step commented out so we can inspect the artifacts on the workflow page but don't actually create new releases on GitHub)? It LGTM but would rather be certain

Check out this job: https://github.com/osohq/oso/runs/4267988765?check_suite_focus=true#step:4:1

**Review by gj — APPROVED** [review]
Thanks!

**Review by gj — CHANGES_REQUESTED** [review]
oh wait remove your testing stuff first 😆

**Review by gj — APPROVED** [review]

**Pull request merged**
