### PR TITLE
(Java): Support M1

### PR DESCRIPTION
**Pull request by hobofan**
- Bumps jnr-ffi to a newer version with Apple Silicon support.
- Updates release workflow to build a fat (x86_64 + aarch64) .dylib and to use that in the .jar build

Fixes the issue I mentioned in https://github.com/osohq/oso/issues/808#issuecomment-1023495977 (at least partially?).

~With the newer version I was able to build the .jar on a M1 machine and the final resulting .jar ran as expected with a aarch64 JRE. However the resulting .jar didn't run on the x86 JRE anymore (though I guess that is expected behavior).~

~Not sure how the .dylib for the release build is built (as the java Makefile references a debug build and specificlally makes a note that it shouldn't be used in release builds?), but I would assume that for properly building a fat .jar some additional step of cross-compiling and building a fat .dylib might be required.~

EDIT: updated PR to include a build of a fat .dylib

### CODE REVIEW

**Comment by hobofan** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by dhatch — APPROVED** [review]

**Comment by dhatch** [comment]
Thanks @hobofan! This is a good step towards M1 support. We'll need to update our CI workflows as well.

**Comment by hobofan** [comment]
Somehow I didn't think to look in the Github actions for the release build 🤦.

I updated the PR with a commit that includes the required changes to make the .jar work in a cross-architecture way on macOS in the release build.

**Comment by unredundant** [comment]
Any ETA for when this will go live? Currently a blocker in my exploration of Oso :)

**Comment by gj** [comment]
Hey @hobofan / @unredundant, sorry for the slow turnaround on this. I'm gonna review it today and we'll hopefully have a new release out shortly.

**Comment by gj** [comment]
Hey @hobofan / @unredundant, sorry for the slow turnaround on this one. @saolsen will take a look at this PR when he's back on Tuesday.

**Comment by unredundant** [comment]
Sorry for being annoying, but any update on this? Pretty excited to try oso but I can't until this issue is resolved :(

**Comment by gneray** [comment]
Hey @unredundant, sorry for for the lack of movement here. Let me look into this, and you'll see an update here (one way or another) in the next few days.

**Comment by saolsen** [comment]
Hey guys, my bad. I just verified this works so merging it now.

**Review by gj — APPROVED** [review]
@saolsen approves

**Pull request merged**
