### PR TITLE
do not raise for multiple parents error when results are empty

### PR DESCRIPTION
**Pull request by lp**
### Why

_the relationship handler should not raise a multiple-parent error when results are empty_

### CODE REVIEW

**Comment by lp** [comment]
env:
    GITHUB_TOKEN: ***
    PERSONAL_ACCESS_TOKEN: ***

**Comment by lp** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by samscott89 — COMMENTED** [review]
Thanks for the PR!

This change looks pretty reasonable, though I'm a little wary of merging this without first understanding what behaviour this is fixing. Do you think it might be possible to add a test case for this (to https://github.com/osohq/oso/blob/main/languages/ruby/spec/oso/polar/data_filtering/gitclub_spec.rb), or elsewhere?

Is this as simple as: if you have a relation that can return one _or none_, we're not currently handling the none case properly?

**Comment by samscott89** [comment]
@lp I added a test in https://github.com/osohq/oso/pull/1623/commits/3b4bd0f5b360516a25573ffe9faf4a1ccbf70359 which I think exhibits the behaviour your contribution is fixing. This fails on main, but passes with your PR.

However, there was one gotcha -- because the adapter using inner joins, we ended up filter _out_ correct results. Could you take a look at https://github.com/osohq/oso/pull/1623/commits/bf417e3feced7510587a8f47047ed40a7cb93ff2 and see if that makes sense as a fix?

**Comment by lp** [comment]
> @lp I added a test in [3b4bd0f](https://github.com/osohq/oso/commit/3b4bd0f5b360516a25573ffe9faf4a1ccbf70359) which I think exhibits the behaviour your contribution is fixing. This fails on main, but passes with your PR.
> 
> However, there was one gotcha -- because the adapter using inner joins, we ended up filter _out_ correct results. Could you take a look at [bf417e3](https://github.com/osohq/oso/commit/bf417e3feced7510587a8f47047ed40a7cb93ff2) and see if that makes sense as a fix?

thanks for the test @samscott89
and the joins tweak fully makes sense

**Review by samscott89 — APPROVED** [review]
Thanks for finding this and figuring out the problem!

**Pull request merged**
