### PR TITLE
Querying `Oso` doesn't need a mutable reference.

### PR DESCRIPTION
**Pull request by samscott89**
Addresses #773 

PR checklist:

- [x] Added changelog entry.

### CODE REVIEW

**Review by gj — COMMENTED** [review]
What about `clear_rules()`, `check_inline_queries()`, `load_file()`, and `load_str()`?

**Comment by samscott89** [comment]
> 
> 
> What about `clear_rules()`, `check_inline_queries()`, `load_file()`, and `load_str()`?

My initial reaction was "no of course not, those mutate inner". But I think you're right. The locking happens in the core. So yes, these should be fine to be immutable refs too.

**Comment by samscott89** [comment]
Also tested against the quickstart: https://github.com/osohq/oso-rust-quickstart/pull/1

**Review by gj — APPROVED** [review]
LGTM, but is this now a major version bump? Can't tell how "breaking" of a change it is. `rustc` will be able to tell end users that they can remove the `mut` designator, but will that be a warning or something that actually causes builds to fail?

**Comment by samscott89** [comment]
> 
> 
> LGTM, but is this now a major version bump? Can't tell how "breaking" of a change it is. `rustc` will be able to tell end users that they can remove the `mut` designator, but will that be a warning or something that actually causes builds to fail?

It will be a warning, yes. Like in the quickstart we get:

```
warning: variable does not need to be mutable
  --> src/server.rs:59:13
   |
59 |         let mut guard = self.oso.lock().unwrap();
   |             ----^^^^^
   |             |
   |             help: remove this `mut`
   |
   = note: `#[warn(unused_mut)]` on by default
```

This would cause build to fail if they check for linter errors/deny warning (like we do), but I feel like this is reasonable for a minor bump

**Pull request merged**
