### PR TITLE
Fix broken data_access example of How-to RBAC guide with sqlalchemy-oso

### PR DESCRIPTION
**Pull request by fconil**
- fixed the setup.py to be installed with "pip install -e ."
- add an arbitrary __version__ string in sqlalchemy_example/__init__.py
(required by setup.py)
- replace example.ipynb with example.py
- checked that unit test worked

### CODE REVIEW

**Review by gkaemmer — APPROVED** [review]
This looks good to me -- thanks for fixing this up. When you get a chance, can you follow the instructions from the CLA bot? It looks like it may require connecting your git email to your github account.

Once that's done, we can get this merged!

**Comment by fconil** [comment]
Sorry I made a mistake, I didn't change the email address to my gmail address linked to my github account before committing.
I will change this and make new PR ?

**Comment by gj** [comment]
> Sorry I made a mistake, I didn't change the email address to my gmail address linked to my github account before committing.
> I will change this and make new PR ?

If you want, you could edit the commit author and force push the same commit:

```
git commit --amend --author="Your Name <your@git.email>" --no-edit
git push --force-with-lease
```

**Comment by fconil** [comment]
Thanks a lot Gabe for the git commands !
As my branch was behind the main, I made new PR. I have to learn more on PR and make more contributions to open source projects :)

**Comment by gj** [comment]
> Thanks a lot Gabe for the git commands !
> As my branch was behind the main, I made new PR. I have to learn more on PR and make more contributions to open source projects :)

Quite all right! Your contributions are much appreciated ❤️ 

Gonna close this one now in favor of #1142

**Pull request closed without merging**
