### PR TITLE
Uniform ExternalOp errors

### PR DESCRIPTION
**Pull request by gj**
PR checklist:

- [x] Added changelog entry.

### CODE REVIEW

**Comment by dhatch** [comment]
Is this based on the Rust `UnimplementedOperation` error?

**Comment by gj** [comment]
> Is this based on the Rust `UnimplementedOperation` error?

Yes. Is that bad?

**Comment by dhatch** [comment]
Not really, just the Rust errors are definitely not finalized, so I wouldn't try to mirror every library off of them yet.  But I think this particular one (UnimplementedOperation) is reasonable to have more broadly.

**Comment by dhatch** [comment]
So if I'm reading this properly, we only support these in Python? Could you make sure we have a follow up in notion for this (not certain we do)?

**Review by dhatch — APPROVED** [review]
lgtm

**Pull request merged**
