### PR TITLE
Rename actor_role predicate to actor_has_role_for_resource

### PR DESCRIPTION
**Pull request by leina05**
Not sure if docs updates should be included here or if docs branches should be rebased after this is merged, @gj .
 EDIT: docs will happen as follow-up.

### CODE REVIEW

**Review by gj — APPROVED** [review]

**Comment by gj** [comment]
> Not sure if docs updates should be included here or if docs branches should be rebased after this is merged, @gj .

Do you mean updates for the new Quickstarts?

**Comment by leina05** [comment]
> > Not sure if docs updates should be included here or if docs branches should be rebased after this is merged, @gj .
> 
> Do you mean updates for the new Quickstarts?

yes

**Comment by gj** [comment]
> > Do you mean updates for the new Quickstarts?
> 
> yes

update after shipping this; I'll create a follow-up task in Notion

**Comment by gj** [comment]
no quickstart entry specifically needed for this PR; it'll be part of the larger entry we need to write for the new Polar roles feature

**Pull request merged**
