### PR TITLE
Enable RuboCop + Solargraph checks in CI

### PR DESCRIPTION
**Pull request by gj**
Came across this stuff while using the Ruby lib as the template for the forthcoming JS lib.

### CODE REVIEW

**Comment by saolsen** [comment]
Can we add rubocop to the tests like we do for rustfmt, clippy and black?

**Comment by gj** [comment]
> Can we add rubocop to the tests like we do for rustfmt, clippy and black?

That's a good idea. I'll look into it.

**Comment by gj** [comment]
Well, yes it's trivially possible to add it to the tests, but we currently have 57 offenses haha. Will fix; shouldn't take long.

**Comment by plotnick** [comment]
Could you please add a `Makefile` target, like `clippy`? I like to run these things locally before I push.

**Comment by gj** [comment]
> Could you please add a `Makefile` target, like `clippy`? I like to run these things locally before I push.

#317

**Pull request merged**
