### PR TITLE
cache by build instead of workflow

### PR DESCRIPTION
**Pull request by saolsen**

### CODE REVIEW

**Comment by samscott89** [comment]
What's the advantage of this over per-workflow? The two wont have the same caches. `cargo build --release` wont build the bench targets for example?

**Comment by saolsen** [comment]
https://github.com/osohq/oso/pull/399/files/db20c9eb230d0d75b83640b9555af1f87fc06198#diff-2e7822c9495b4cd7a05389935ddc44ed

I sorta might agree though, if bench has different dependencies than just the release build it might make sense to continue cacheing them separately.

**Comment by gj** [comment]
> What's the advantage of this over per-workflow? The two wont have the same caches. `cargo build --release` wont build the bench targets for example?

Just tested this locally to confirm that `cargo bench` and `cargo build --release` overlap, significantly decreasing compile time over compiling both independently. `cargo bench` doesn't build the `polar-wasm-api` crate, and yes `cargo build --release` won't build the bench targets, but I think this is still worth doing.

**Review by gj — APPROVED** [review]
Wait for @samscott89's approval as well, but this is fine by me

**Review by samscott89 — APPROVED** [review]

**Pull request merged**
