### PR TITLE
refactor: simplify logical expression using De Morgan identities

### PR DESCRIPTION
**Pull request by kkirsche**
When reading logical statements it is important for them to be as simple as possible. This proposal applies De Morgan's laws to simplify code by pushing negations deeper into the statement.

PR checklist:

- [ ] Added changelog entry.

### CODE REVIEW

**Comment by gw000** [comment]
This is fine, but honestly I'd rather remove the error entirely. What do we gain by requiring people to use a specific file extension? @gj @samscott89 any thoughts?

**Comment by gj** [comment]
> This is fine, but honestly I'd rather remove the error entirely. What do we gain by requiring people to use a specific file extension? @gj @samscott89 any thoughts?

Possibly not much, but I'd rather avoid thinking about the answer to that question for now and just ship this as-is. FWIW, it's something that has come up in the past — I believe @plotnick asked the same question & I gave the same answer 😅

**Comment by gw000** [comment]
Alas https://youtu.be/cOeKidp-iWo

**Review by gw000 — APPROVED** [review]
Thank you! 🙂

**Pull request merged**
