### PR TITLE
Improved formatting & imports for Python's oso and sqlalchemy-oso 

### PR DESCRIPTION
**Pull request by tomashozman**
I messed up the previous pull request and decided to try again a new one - sorry about that. This one should be better and _hopefully_ pass the checks.

Original PR:
---
I've decided to try and improve the formatting and its consistency somewhat, as well as clean up the namespaces a bit. It's still not perfect, and I've probably missed a couple issues, but I think it's way better like this than it was before. I've also added `__all__` variables to a couple `__init__.py` files.
The decision to not indent multi-line strings may be a bit controversial, as well as some other things. I can change those if necessary.
Please let me know what you think.

### CODE REVIEW

**Comment by tomashozman** [comment]
Oh, are we using SQLAlchemy 1.3 for `oso/tests/polar_roles_sqlalchemy_helpers.py`? The `requirements.txt` say it's 1.4, though.
`declared_attr` should be in `orm` there.

**Comment by samscott89** [comment]
Hey @tomashozman!

Thanks for opening this PR!

Did you use any tools to generate these formatting changes? It could be tough for us to review a ~1k line diff line-by-line. It would be a lot easier if we could first commit any auto-formatting changes first.

**Comment by tomashozman** [comment]
Hello!
The docstring / comment formatting was manual, as well as the slight namespace changes. The rest was `isort` and auto-formatting it with Black, just in case I've missed anything.
Also, speaking of missing things...

**Comment by tomashozman** [comment]
I'm not sure what's wrong with the SQLAlchemy import near the end of Python's check. It's probably a rookie mistake, perhaps somebody else can figure it out.

**Comment by samscott89** [comment]
Hey @tomashozman.

We really appreciate the effort you put into this, but at this time we aren't able to review large PRs which have mostly formatting changing. We rely on automatic formatting tools to handle those for us. We would consider a PR which added some additional tooling like `isort` to clean up imports.

Alternatively, you could look at some of the [good first issues](https://github.com/osohq/oso/issues?q=is%3Aissue+label%3A%22good+first+issue%22+is%3Aopen) we have listed.

Again, many thanks for the effort in this contribution, and sorry we couldn't help you get this merged.

**Pull request closed without merging**
