### PR TITLE
Singleton variables are errors

### PR DESCRIPTION
**Pull request by gw000**
What it does:

- singleton variables are now errors!
- fixes a bug where SingletonVisitor wasn't walking dicts contained in
  patterns
- updates the singleton variable test, and removes singleton variables
  from other tests

What it doesn't do but maybe should:

- let users choose the old behavior (emit a warning)

PR checklist:

- [x] Added changelog entry.

### CODE REVIEW

**Comment by gw000** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by saolsen — APPROVED** [review]
Looks Great!

**Comment by saolsen** [comment]
Changelog and msg look good, you can merge it when the tests pass!

**Comment by gw000** [comment]
It's listed in the changelog as a breaking change, and the error message is updated to include the fix, which is very easy. So we're not going to add a compatibility option.

**Pull request merged**
